import * as p from "@clack/prompts";
import { writeFile, mkdir } from "node:fs/promises";
import { printBanner } from "./banner.js";
import { brand, brandBg, icons, bold } from "./ui.js";

export async function initDocs(version = "4.1.0") {
  // V0.2 deprecation warning — the recommended path is the Claude Code skill flow.
  console.warn(
    "\x1b[33m" +
      "⚠ DeprecationWarning: `bridge-ds init-docs` is deprecated in v4.1.0.\n" +
      "   The recommended setup flow runs in Claude Code via `setup bridge`.\n" +
      "   The CLI command still works but will be removed in v5.0.0.\n" +
      "   See: https://github.com/noemuch/bridge/blob/main/CHANGELOG.md" +
      "\x1b[0m\n"
  );

  printBanner("Compiler-driven design system docs", version);
  console.log(" " + brandBg(" bridge init-docs ") + "\n");

  p.intro("Setup Bridge Docs");

  p.log.step(`${bold("[1/4]")} ${brand("Design System identity")}`);
  const dsName = await p.text({
    message: "What's your DS called?",
    placeholder: "Spectra",
    validate: (v) => ((v ?? "").length === 0 ? "Required" : undefined),
  });
  if (p.isCancel(dsName)) {
    p.cancel("Cancelled");
    return;
  }

  const repo = await p.text({
    message: "GitHub repo (for cron PR target)?",
    placeholder: "acme/design-system",
  });
  if (p.isCancel(repo)) {
    p.cancel("Cancelled");
    return;
  }

  p.log.step(`${bold("[2/4]")} ${brand("Figma connection")}`);
  const tokenMode = await p.select({
    message: "How should the cron talk to Figma?",
    options: [
      { value: "pat", label: "Figma Personal Access Token (recommended)" },
      { value: "skip", label: "Skip — configure later" },
    ],
  });
  if (p.isCancel(tokenMode)) {
    p.cancel("Cancelled");
    return;
  }

  let figmaToken = "";
  let figmaFileKey = "";
  if (tokenMode === "pat") {
    const tokenRaw = await p.password({
      message: "Figma PAT (saved as GitHub secret FIGMA_TOKEN):",
    });
    if (p.isCancel(tokenRaw)) {
      p.cancel("Cancelled");
      return;
    }
    figmaToken = String(tokenRaw);
    const keyRaw = await p.text({ message: "Figma DS file key:", placeholder: "FILEKEY123" });
    if (p.isCancel(keyRaw)) {
      p.cancel("Cancelled");
      return;
    }
    figmaFileKey = String(keyRaw);
    const s = p.spinner();
    s.start("Validating token…");
    try {
      const r = await fetch(`https://api.figma.com/v1/files/${figmaFileKey}`, {
        headers: { "X-Figma-Token": figmaToken },
      });
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      s.stop(`${icons.pass} Token valid.`);
    } catch (e) {
      s.stop(`${icons.fail} Token validation failed: ${String((e as Error).message)}`);
    }
  }

  p.log.step(`${bold("[3/4]")} ${brand("Cron cadence")}`);
  const cadence = await p.select({
    message: "How often should the cron check for drift?",
    options: [
      { value: "daily", label: "Daily — 06:00 UTC (recommended)" },
      { value: "weekly", label: "Weekly — Monday 06:00 UTC" },
    ],
  });
  if (p.isCancel(cadence)) {
    p.cancel("Cancelled");
    return;
  }

  p.log.step(`${bold("[4/4]")} ${brand("Scaffolding")}`);
  const s2 = p.spinner();
  s2.start("Creating directory structure…");
  await mkdir("bridge-ds/knowledge-base/registries", { recursive: true });
  await mkdir("design-system/components", { recursive: true });
  await mkdir("design-system/foundations", { recursive: true });
  await mkdir("design-system/_manual", { recursive: true });
  await mkdir(".bridge", { recursive: true });
  await mkdir(".github/workflows", { recursive: true });

  await writeFile(
    "docs.config.yaml",
    `dsName: "${String(dsName)}"\nfigmaFileKey: "${figmaFileKey}"\ndocsPath: "design-system"\nkbPath: "bridge-ds"\ncron:\n  cadence: "${String(cadence)}"\n  time: "06:00"\n`
  );
  await writeFile("llms.txt", `# ${String(dsName)}\n\n> Generated by Bridge Docs.\n`);
  await writeFile(
    ".bridge/mcp.json",
    JSON.stringify(
      {
        mcpServers: {
          "bridge-ds": { command: "npx", args: ["@noemuch/bridge-ds", "docs", "mcp"], env: {} },
        },
      },
      null,
      2
    )
  );
  s2.stop(`${icons.pass} Scaffolding complete.`);

  p.note(
    `Open this repo in Claude Code or Cursor and say:\n\n    setup\n\nThen:\n\n    make <description>\n\nGitHub Action secret to add:\n    FIGMA_TOKEN = ${figmaToken.slice(0, 10)}…\nAdd at: https://github.com/${String(repo)}/settings/secrets/actions`,
    "Next steps"
  );

  p.outro(`${icons.info} Happy designing.`);
}
